config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks }
  root controller: :welcome, action: :index

  authenticate :user do
    get :dashboard, controller: :welcome, action: :dashboard
    resources :groups, only: [:new, :create, :show, :destroy] do
      resources :expenses, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :description, presence: true
  validates :amount, presence: true
  belongs_to :group
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  has_and_belongs_to_many :users
  has_many :expenses
end

app/models/user.rb
class User < ApplicationRecord
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  has_and_belongs_to_many :groups
  has_many :expenses
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

   def self.new_with_session(params, session)
     super.tap do |user|
       if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
         user.email = data['email'] if user.email.blank?
       end
     end
   end

   def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
     end
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def create
    @expense = Expense.new(expense_params.merge(group_id: params[:group_id]))
    add_current_user_to_expense

    @group = Group.find(params[:group_id])
    all_group_expenses = extract_user_expenses(@group)
    total_amounts_owed = calculate_amounts(all_group_expenses)
    output = split(all_group_expenses, total_amounts_owed)
    @group.output = output
    @group.save

    render 'groups/show'
  end

  private

  def expense_params
    params.require(:expense).permit(:description, :amount, :group_id)
  end

  def add_current_user_to_expense
    @expense.user = current_user
    @expense.save
  end

  def calculate_amounts(group)
    @group_average = group.values.reduce(:+).fdiv(@group.users.length)
    group.map {|k, v| [k, (v - @group_average).round(2)]}.to_h
  end

  def extract_user_expenses(group)
    total_expenses = {}
    group.users.each do |user|
      total_expenses[user.email] = 0
    end
    group.expenses.each do |expense|
      total_expenses[expense.user.email] += expense.amount
    end
    total_expenses
  end

  def split(all_group_expenses, total_amounts_owed)
    lenders = []
    debtors = []
    output = ["Total expenses per person: #{@group_average.to_i}kr"]

    all_group_expenses.each do |email, amount|
      next if total_amounts_owed[email] == 0
      if amount > @group_average
        lenders << { email => total_amounts_owed[email] }
      else
        debtors << { email => total_amounts_owed[email] }
      end
    end

    lenders.each do |lender|
      if lender.values.first != 0
        debtors.each do |debtor|
          debtor_owes = debtor.values.first
          debtor_email = debtor.keys.first
          lender_owed = lender.values.first
          lender_email = lender.keys.first

          next if lender_owed == 0 || debtor_owes == 0
          if (lender_owed >= debtor_owes.abs)
            lender[lender_email] = (lender_owed + debtor_owes)
            output << "#{debtor_email} owes #{lender_email} #{-(debtor_owes.to_i)}kr"
            debtor[debtor_email] = (debtor_owes - debtor_owes)

          else
            debtor[debtor_email] =  (debtor_owes + lender_owed)
            output << "#{debtor_email} owes #{lender_email} #{lender_owed.to_i}kr"
            lender[lender_email] = (lender_owed - lender_owed)
          end
        end
      end
    end
    output
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @users_list = User.all.to_a
    @users_list.delete_at(@users_list.index(current_user))
  end

  def create
    params[:users].shift
    @group = Group.new(group_params)
    @group.owner = current_user.email
    add_users_to_group
    add_current_user_to_group
    @group.save
    redirect_to group_path(@group)
  end

  def show
    @group = Group.find_by(id: params[:id])
  end

  def destroy
    group = Group.find_by(id: params[:id])
    if group.owner == current_user.email
      group.destroy
      flash[:success] = "#{group.name} was successfully deleted"
      redirect_to dashboard_path
    else
      flash[:error] = "Only #{group.owner} can delete this group"
      redirect_to group_path(group)
    end
  end

  private

  def group_params
    params.permit(:name, :description, :users)
  end

  def add_users_to_group
    params[:users].each do |member|
      user = User.find_by(id: member)
      @group.users << user
    end
  end

  def add_current_user_to_group
    @group.users << current_user
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path, notice: 'Well that didn\'t work..'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path, notice: 'Well that didn\'t work..'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    redirect_to dashboard_path if user_signed_in?
  end

end

app/views/groups/new.html.erb
<h3> Create a group </h3>

<div class='form-group'>
  <%= form_with url: groups_path do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, id: 'Name', class: 'form-control', placeholder: 'Name your group' %>
    <%= f.label :description %>
    <%= f.text_field :description, id: 'Description', class: 'form-control', placeholder: 'Give your group a description' %>
    <%= f.label :select %>
    <%= f.select(:users, @users_list.collect {|u| [ u.email, u.id ] }, {}, { multiple: true, id: 'friends', class: 'form-control' })%>
    <%= f.submit value: 'Create group' , class: 'btn btn-success' %>
  <% end %>
</div>

app/views/groups/show.html.erb
<h1> <%= @group.name %> </h1>

<p> <%= @group.description %> </p>

<h3> Members </h3>
<% @group.users.each do |user| %>
  <p>
    <% if user == current_user %>
      <strong>
        <%= user.email %>
      </strong>
    <% else %>
      <%= user.email %>
    <% end %>
  </p>
<% end %>

<div class='form-group'>
  <%= form_with model: [@group, Expense.new], local: true do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description, id: 'Description', class:'form-control', placeholder: 'Describe your expense' %>

  <%= f.label :amount %>
  <%= f.text_field :amount, id: 'Amount', class:'form-control', placeholder: 'How much did you spend?' %>
  <%= f.submit value: 'Add expense', class:'btn btn-success' %>
  <% end %>
</div>
<br>
<h3>Expense History</h3>
<% @group.expenses.each do |expense| %>
  <p><%= expense.user.email %> paid <%= expense.amount %>kr for <%= expense.description %></p>
<% end %>
<br>
<h3> Who owes whom?</h3>
<% @group.output.each do |message| %>
  <p><%= message %> <br></p>  
<% end %>
<br>
<%= link_to 'Delete Group', group_path(@group), method: :delete, class: 'btn btn-danger' %>

app/views/layouts/_nav.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <% if user_signed_in? %>
      <h4><%= "Hello, #{current_user.email[0..8]}.." %></h4>
      <li><%= link_to 'Dashboard', dashboard_path %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <h4>My Groups</h4>
      <% current_user.groups.reverse.each do |group| %>
        <li><%= link_to group.name, group_path(group)%></li>
      <% end %>
    <% else %>
      <div class ='new-nav'>
        <li>
          <%= link_to 'Login', new_user_session_path %>
        </li>
        <li>
          <%= link_to 'Register', new_user_registration_path %>
        </li>
        <li>
          <% unless current_user %>
            <%= link_to 'Facebook Sign in', user_facebook_omniauth_authorize_path %>
          <% end %>
        </li>
      </div>
      <% end %>
    </ul>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evensteven</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper" class="toggled">

    <%= render 'layouts/nav' %>

    <% flash.each do |key, value| %>
      <div class="text-center">
        <%= value %>
      </div>
    <% end %>
    <!-- Page Content -->
    <div id="page-content-wrapper">
        <div class="container-fluid">
          <%= yield %>
        </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>

  <!-- Menu Toggle Script -->
  <script>
  $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
  });
  </script>

  </body>
</html>

app/views/welcome/dashboard.html.erb
<h1> Dashboard </h1>
<%= link_to 'Create a group', new_group_path, class: 'btn btn-success' %>

<div>
<% current_user.groups.each do |group| %>
  <div>
    <br>
    <h1><%= group.name %> Summary </h1>
    <% group.output.each do |output|%>
        <p> <%= output %> <br> </p>
    <% end %>
  </div>
<% end %>
</div>

app/views/welcome/index.html.erb
<div class='title-text'>
  <h1>Even Steven</h1>
  <p>
    The easiest way to split your bills and pay your friends.<br />
    Cuz mo' money doesn't have to mean mo' problems.
  </p>
</div>